#ifndef LexerFileTokens_HPP
#define LexerFileTokens_HPP

#undef NULL

namespace LexerFileTokens
{
    const int END = 0;
    const int CLASSMAP = 1;
    const int PREFIX = 2;
    const int TOKENS = 3;
    const int KEYWORDS = 4;
    const int EXPRESSIONS = 5;
    const int LEXER = 6;
    const int VARIABLES = 7;
    const int ACTIONS = 8;
    const int API = 9;
    const int INCLUDE = 10;
    const int FILEPATH = 11;
    const int DOLLAR = 12;
    const int AUTO = 13;
    const int REGISTER = 14;
    const int STATIC = 15;
    const int EXTERN = 16;
    const int MUTABLE = 17;
    const int CHAR = 18;
    const int WCHART = 19;
    const int BOOL = 20;
    const int SHORT = 21;
    const int INT = 22;
    const int LONG = 23;
    const int SIGNED = 24;
    const int UNSIGNED = 25;
    const int FLOAT = 26;
    const int DOUBLE = 27;
    const int VOID = 28;
    const int TYPEDEF = 29;
    const int CONST = 30;
    const int VOLATILE = 31;
    const int USING = 32;
    const int NAMESPACE = 33;
    const int THROW = 34;
    const int SIZEOF = 35;
    const int OPERATOR = 36;
    const int DYNAMICCAST = 37;
    const int STATICCAST = 38;
    const int REINTERPRETCAST = 39;
    const int CONSTCAST = 40;
    const int TYPEID = 41;
    const int THIS = 42;
    const int NEW = 43;
    const int DELETE = 44;
    const int TRUE = 45;
    const int FALSE = 46;
    const int NULLPTR = 47;
    const int CASE = 48;
    const int DEFAULT = 49;
    const int IF = 50;
    const int ELSE = 51;
    const int SWITCH = 52;
    const int WHILE = 53;
    const int DO = 54;
    const int FOR = 55;
    const int BREAK = 56;
    const int CONTINUE = 57;
    const int RETURN = 58;
    const int GOTO = 59;
    const int TRY = 60;
    const int CATCH = 61;
    const int ID = 62;
    const int INTLIT = 63;
    const int FLOATINGLIT = 64;
    const int CHARLIT = 65;
    const int STRINGLIT = 66;
    const int DISJUNCTION = 67;
    const int AMPAMP = 68;
    const int DOTSTAR = 69;
    const int ARROWSTAR = 70;
    const int BITOR = 71;
    const int BITXOR = 72;
    const int AMP = 73;
    const int EQ = 74;
    const int NEQ = 75;
    const int LEQ = 76;
    const int GEQ = 77;
    const int SHIFTLEFT = 78;
    const int SHIFTRIGHT = 79;
    const int PLUS = 80;
    const int MINUS = 81;
    const int STAR = 82;
    const int DIV = 83;
    const int REM = 84;
    const int PLUSPLUS = 85;
    const int MINUSMINUS = 86;
    const int CPL = 87;
    const int DOT = 88;
    const int ARROW = 89;
    const int NOT = 90;
    const int QUEST = 91;
    const int LPAREN = 92;
    const int RPAREN = 93;
    const int LBRACE = 94;
    const int RBRACE = 95;
    const int LBRACKET = 96;
    const int RBRACKET = 97;
    const int LANGLE = 98;
    const int RANGLE = 99;
    const int ELLIPSIS = 100;
    const int COLONCOLON = 101;
    const int COLON = 102;
    const int SEMICOLON = 103;
    const int HASH = 104;
    const int COMMA = 105;
    const int ASSIGN = 106;
    const int MULASSIGN = 107;
    const int DIVASSIGN = 108;
    const int REMASSIGN = 109;
    const int PLUSASSIGN = 110;
    const int MINUSASSIGN = 111;
    const int SHIFTLEFTASSIGN = 112;
    const int SHIFTRIGHTASSIGN = 113;
    const int ANDASSIGN = 114;
    const int XORASSIGN = 115;
    const int ORASSIGN = 116;

    int GetTokenId(const std::u32string& tokenName);
    const char* GetTokenName(int tokenId);
    const char* GetTokenInfo(int tokenId);
}
#endif
