@echo off
xcopy /Y /D ..\soulng\x64\Debug\sngutild.lib ..\lib
xcopy /Y /D ..\soulng\x64\Release\sngutil.lib ..\lib
xcopy /Y /D ..\soulng\x64\Debug\sngcppcoded.lib ..\lib
xcopy /Y /D ..\soulng\x64\Release\sngcppcode.lib ..\lib
xcopy /Y /D ..\soulng\x64\Debug\snglexerd.lib ..\lib
xcopy /Y /D ..\soulng\x64\Release\snglexer.lib ..\lib
xcopy /Y /D ..\soulng\x64\Debug\sngparserd.lib ..\lib
xcopy /Y /D ..\soulng\x64\Release\sngparser.lib ..\lib
xcopy /Y /D ..\soulng\x64\Debug\sngutild.dll ..\bin
xcopy /Y /D ..\soulng\x64\Release\sngutil.dll ..\bin
xcopy /Y /D ..\soulng\x64\Debug\sngcppcoded.dll ..\bin
xcopy /Y /D ..\soulng\x64\Release\sngcppcode.dll ..\bin
xcopy /Y /D ..\soulng\x64\Debug\snglexerd.dll ..\bin
xcopy /Y /D ..\soulng\x64\Release\snglexer.dll ..\bin
xcopy /Y /D ..\soulng\x64\Debug\sngparserd.dll ..\bin
xcopy /Y /D ..\soulng\x64\Release\sngparser.dll ..\bin
xcopy /Y /D ..\soulng\x64\Debug\slgd.exe ..\bin
xcopy /Y /D ..\soulng\x64\Release\slg.exe ..\bin
xcopy /Y /D ..\soulng\x64\Debug\spgd.exe ..\bin
xcopy /Y /D ..\soulng\x64\Release\spg.exe ..\bin
xcopy /Y /D ..\soulng\x64\Debug\sngrexd.lib ..\lib
xcopy /Y /D ..\soulng\x64\Debug\sngrexd.dll ..\bin
xcopy /Y /D ..\soulng\x64\Release\sngrex.lib ..\lib
xcopy /Y /D ..\soulng\x64\Release\sngrex.dll ..\bin
xcopy /Y /D ..\examples\minilang\x64\Debug\minilangd.exe ..\bin
xcopy /Y /D ..\examples\minilang\x64\Release\minilang.exe ..\bin
xcopy /Y /D ..\sngxml\x64\Debug\sngxmlxmld.lib ..\lib
xcopy /Y /D ..\sngxml\x64\Release\sngxmlxml.lib ..\lib
xcopy /Y /D ..\sngxml\x64\Debug\sngxmldomd.lib ..\lib
xcopy /Y /D ..\sngxml\x64\Release\sngxmldom.lib ..\lib
xcopy /Y /D ..\sngxml\x64\Debug\sngxmlxpathd.lib ..\lib
xcopy /Y /D ..\sngxml\x64\Release\sngxmlxpath.lib ..\lib
xcopy /Y /D ..\sngxml\x64\Debug\sngxmlxmld.dll ..\bin
xcopy /Y /D ..\sngxml\x64\Release\sngxmlxml.dll ..\bin
xcopy /Y /D ..\sngxml\x64\Debug\sngxmldomd.dll ..\bin
xcopy /Y /D ..\sngxml\x64\Release\sngxmldom.dll ..\bin
xcopy /Y /D ..\sngxml\x64\Debug\sngxmlxpathd.dll ..\bin
xcopy /Y /D ..\sngxml\x64\Release\sngxmlxpath.dll ..\bin
xcopy /Y /D ..\sngxml\x64\Debug\sngxmltesterd.exe ..\bin
xcopy /Y /D ..\sngxml\x64\Release\sngxmltester.exe ..\bin
xcopy /Y /D ..\sngcpp\bin\*.* ..\bin
xcopy /Y /D ..\sngcpp\lib\*.* ..\lib
xcopy /Y /D ..\sngcm\bin\*.* ..\bin
xcopy /Y /D ..\sngcm\lib\*.* ..\lib
xcopy /Y /D ..\tools\gendoc\x64\Debug\gendochtmld.lib ..\lib
xcopy /Y /D ..\tools\gendoc\x64\Debug\gendochtmld.dll ..\bin
xcopy /Y /D ..\tools\gendoc\x64\Release\gendochtml.lib ..\lib
xcopy /Y /D ..\tools\gendoc\x64\Release\gendochtml.dll ..\bin
xcopy /Y /D ..\tools\gendoc\x64\Debug\gendocd.exe ..\bin
xcopy /Y /D ..\tools\gendoc\x64\Release\gendoc.exe ..\bin
xcopy /Y /D ..\tools\cpp2cm\x64\Debug\cpp2cmd.exe ..\bin
xcopy /Y /D ..\tools\cpp2cm\x64\Release\cpp2cm.exe ..\bin
