@echo off
xcopy /Y /D ..\soulng\x64\Debug\sngutild.lib ..\lib
xcopy /Y /D ..\soulng\x64\Release\sngutil.lib ..\lib
xcopy /Y /D ..\soulng\x64\Debug\sngcppcoded.lib ..\lib
xcopy /Y /D ..\soulng\x64\Release\sngcppcode.lib ..\lib
xcopy /Y /D ..\soulng\x64\Debug\snglexerd.lib ..\lib
xcopy /Y /D ..\soulng\x64\Release\snglexer.lib ..\lib
xcopy /Y /D ..\soulng\x64\Debug\sngparserd.lib ..\lib
xcopy /Y /D ..\soulng\x64\Release\sngparser.lib ..\lib
xcopy /Y /D ..\soulng\x64\Debug\sngutild.dll ..\bin
xcopy /Y /D ..\soulng\x64\Release\sngutil.dll ..\bin
xcopy /Y /D ..\soulng\x64\Debug\sngcppcoded.dll ..\bin
xcopy /Y /D ..\soulng\x64\Release\sngcppcode.dll ..\bin
xcopy /Y /D ..\soulng\x64\Debug\snglexerd.dll ..\bin
xcopy /Y /D ..\soulng\x64\Release\snglexer.dll ..\bin
xcopy /Y /D ..\soulng\x64\Debug\sngparserd.dll ..\bin
xcopy /Y /D ..\soulng\x64\Release\sngparser.dll ..\bin
xcopy /Y /D ..\soulng\x64\Debug\slgd.exe ..\bin
xcopy /Y /D ..\soulng\x64\Release\slg.exe ..\bin
xcopy /Y /D ..\soulng\x64\Debug\spgd.exe ..\bin
xcopy /Y /D ..\soulng\x64\Release\spg.exe ..\bin
xcopy /Y /D ..\soulng\x64\Debug\sngrexd.lib ..\lib
xcopy /Y /D ..\soulng\x64\Debug\sngrexd.dll ..\bin
xcopy /Y /D ..\soulng\x64\Release\sngrex.lib ..\lib
xcopy /Y /D ..\soulng\x64\Release\sngrex.dll ..\bin
xcopy /Y /D ..\examples\minilang\x64\Debug\minilangd.exe ..\bin
xcopy /Y /D ..\examples\minilang\x64\Release\minilang.exe ..\bin
xcopy /Y /D ..\sngxml\x64\Debug\sngxmlxmld.lib ..\lib
xcopy /Y /D ..\sngxml\x64\Release\sngxmlxml.lib ..\lib
xcopy /Y /D ..\sngxml\x64\Debug\sngxmldomd.lib ..\lib
xcopy /Y /D ..\sngxml\x64\Release\sngxmldom.lib ..\lib
xcopy /Y /D ..\sngxml\x64\Debug\sngxmlxpathd.lib ..\lib
xcopy /Y /D ..\sngxml\x64\Release\sngxmlxpath.lib ..\lib
xcopy /Y /D ..\sngxml\x64\Debug\sngxmlxmld.dll ..\bin
xcopy /Y /D ..\sngxml\x64\Release\sngxmlxml.dll ..\bin
xcopy /Y /D ..\sngxml\x64\Debug\sngxmldomd.dll ..\bin
xcopy /Y /D ..\sngxml\x64\Release\sngxmldom.dll ..\bin
xcopy /Y /D ..\sngxml\x64\Debug\sngxmlxpathd.dll ..\bin
xcopy /Y /D ..\sngxml\x64\Release\sngxmlxpath.dll ..\bin
xcopy /Y /D ..\sngxml\x64\Debug\sngxmltesterd.exe ..\bin
xcopy /Y /D ..\sngxml\x64\Release\sngxmltester.exe ..\bin
xcopy /Y /D ..\sngcpp\bin\*.* ..\bin
xcopy /Y /D ..\sngcpp\lib\*.* ..\lib
xcopy /Y /D ..\sngcm\bin\*.* ..\bin
xcopy /Y /D ..\sngcm\lib\*.* ..\lib
xcopy /Y /D ..\tools\gendoc\x64\Debug\gendochtmld.lib ..\lib
xcopy /Y /D ..\tools\gendoc\x64\Debug\gendochtmld.dll ..\bin
xcopy /Y /D ..\tools\gendoc\x64\Release\gendochtml.lib ..\lib
xcopy /Y /D ..\tools\gendoc\x64\Release\gendochtml.dll ..\bin
xcopy /Y /D ..\tools\gendoc\x64\Debug\gendocd.exe ..\bin
xcopy /Y /D ..\tools\gendoc\x64\Release\gendoc.exe ..\bin
xcopy /Y /D ..\tools\cpp2cm\x64\Debug\cpp2cmd.exe ..\bin
xcopy /Y /D ..\tools\cpp2cm\x64\Release\cpp2cm.exe ..\bin
xcopy /Y /D ..\tools\snginst\x64\Debug\snginstd.exe ..\bin
xcopy /Y /D ..\tools\snginst\x64\Release\snginst.exe ..\bin
xcopy /Y /D ..\sngcpp20\x64\Debug\sngcpp20_astd.dll ..\bin
xcopy /Y /D ..\sngcpp20\x64\Debug\sngcpp20_astd.lib ..\lib
xcopy /Y /D ..\sngcpp20\x64\Debug\sngcpp20_lexerd.dll ..\bin
xcopy /Y /D ..\sngcpp20\x64\Debug\sngcpp20_lexerd.lib ..\lib
xcopy /Y /D ..\sngcpp20\x64\Debug\sngcpp20_lexerd.lib ..\lib
xcopy /Y /D ..\sngcpp20\x64\Debug\sngcpp20_symbolsd.dll ..\bin
xcopy /Y /D ..\sngcpp20\x64\Debug\sngcpp20_symbolsd.lib ..\lib
xcopy /Y /D ..\sngcpp20\x64\Debug\sngcpp20_parserd.dll ..\bin
xcopy /Y /D ..\sngcpp20\x64\Debug\sngcpp20_parserd.lib ..\lib
xcopy /Y /D ..\sngcpp20\x64\Debug\sngcpp20_projectd.dll ..\bin
xcopy /Y /D ..\sngcpp20\x64\Debug\sngcpp20_projectd.lib ..\lib
xcopy /Y /D ..\sngcpp20\x64\Debug\sngcpp20_ppd.dll ..\bin
xcopy /Y /D ..\sngcpp20\x64\Debug\sngcpp20_ppd.lib ..\lib
xcopy /Y /D ..\sngcpp20\x64\Debug\sngcpp20_driverd.dll ..\bin
xcopy /Y /D ..\sngcpp20\x64\Debug\sngcpp20_driverd.lib ..\lib
xcopy /Y /D ..\sngcpp20\x64\Debug\sngcppd.exe ..\bin
xcopy /Y /D ..\sngcpp20\x64\Release\sngcpp20_ast.dll ..\bin
xcopy /Y /D ..\sngcpp20\x64\Release\sngcpp20_ast.lib ..\lib
xcopy /Y /D ..\sngcpp20\x64\Release\sngcpp20_lexer.dll ..\bin
xcopy /Y /D ..\sngcpp20\x64\Release\sngcpp20_lexer.lib ..\lib
xcopy /Y /D ..\sngcpp20\x64\Release\sngcpp20_symbols.dll ..\bin
xcopy /Y /D ..\sngcpp20\x64\Release\sngcpp20_symbols.lib ..\lib
xcopy /Y /D ..\sngcpp20\x64\Release\sngcpp20_parser.dll ..\bin
xcopy /Y /D ..\sngcpp20\x64\Release\sngcpp20_parser.lib ..\lib
xcopy /Y /D ..\sngcpp20\x64\Release\sngcpp20_project.dll ..\bin
xcopy /Y /D ..\sngcpp20\x64\Release\sngcpp20_project.lib ..\lib
xcopy /Y /D ..\sngcpp20\x64\Release\sngcpp20_pp.dll ..\bin
xcopy /Y /D ..\sngcpp20\x64\Release\sngcpp20_pp.lib ..\lib
xcopy /Y /D ..\sngcpp20\x64\Release\sngcpp20_driver.dll ..\bin
xcopy /Y /D ..\sngcpp20\x64\Release\sngcpp20_driver.lib ..\lib
xcopy /Y /D ..\sngcpp20\x64\Release\sngcpp.exe ..\bin
