ifeq ($(config),debug)
CXXFLAGS += -pthread -fPIC -std=c++11 -I.. -I../.. -L../../lib -L../../../lib -g -O0
else
CXXFLAGS += -pthread -fPIC -std=c++11 -I.. -I../.. -L../../lib -L../../../lib -DNDEBUG -O3
endif
