include Makefile.common

all:
	$(MAKE) -C util
	$(MAKE) -C lexer
	$(MAKE) -C parser
	$(MAKE) -C cppcode
	$(MAKE) -C slg
	$(MAKE) -C spg

clean:
	$(MAKE) -C util clean
	$(MAKE) -C lexer clean
	$(MAKE) -C parser clean
	$(MAKE) -C cppcode clean
	$(MAKE) -C slg clean
	$(MAKE) -C spg clean
