include ../Makefile.common

all:
	$(MAKE) -C ast
	$(MAKE) -C lexer
	$(MAKE) -C parser
	$(MAKE) -C tester

clean:
	$(MAKE) -C ast clean
	$(MAKE) -C lexer clean
	$(MAKE) -C parser clean
	$(MAKE) -C tester clean
