#ifndef ParserFileTokens_HPP
#define ParserFileTokens_HPP

// this file has been automatically generated from 'C:/work/soulng/soulng/spg/ParserFileLexer.lexer' using soulng lexer generator slg version 3.10.0

#include <string>

namespace ParserFileTokens
{
    const int END = 0;
    const int PARSER = 1;
    const int API = 2;
    const int INCLUDE = 3;
    const int MAIN = 4;
    const int NOTHROW = 5;
    const int STATE = 6;
    const int USELEXER = 7;
    const int RULEINFO = 8;
    const int EMPTY = 9;
    const int ANY = 10;
    const int VAR = 11;
    const int CPPPREFIX = 12;
    const int HPPPREFIX = 13;
    const int FILEPATH = 14;
    const int PRODUCES = 15;
    const int EXCLAMATION = 16;
    const int AUTO = 17;
    const int REGISTER = 18;
    const int STATIC = 19;
    const int EXTERN = 20;
    const int MUTABLE = 21;
    const int CHAR = 22;
    const int WCHART = 23;
    const int BOOL = 24;
    const int SHORT = 25;
    const int INT = 26;
    const int LONG = 27;
    const int SIGNED = 28;
    const int UNSIGNED = 29;
    const int FLOAT = 30;
    const int DOUBLE = 31;
    const int VOID = 32;
    const int TYPEDEF = 33;
    const int CONST = 34;
    const int VOLATILE = 35;
    const int USING = 36;
    const int NAMESPACE = 37;
    const int THROW = 38;
    const int SIZEOF = 39;
    const int OPERATOR = 40;
    const int DYNAMICCAST = 41;
    const int STATICCAST = 42;
    const int REINTERPRETCAST = 43;
    const int CONSTCAST = 44;
    const int TYPEID = 45;
    const int THIS = 46;
    const int NEW = 47;
    const int DELETE = 48;
    const int TRUE = 49;
    const int FALSE = 50;
    const int NULLPTR = 51;
    const int CASE = 52;
    const int DEFAULT = 53;
    const int IF = 54;
    const int ELSE = 55;
    const int SWITCH = 56;
    const int WHILE = 57;
    const int DO = 58;
    const int FOR = 59;
    const int BREAK = 60;
    const int CONTINUE = 61;
    const int RETURN = 62;
    const int GOTO = 63;
    const int TRY = 64;
    const int CATCH = 65;
    const int ID = 66;
    const int INTLIT = 67;
    const int FLOATINGLIT = 68;
    const int CHARLIT = 69;
    const int STRINGLIT = 70;
    const int DISJUNCTION = 71;
    const int AMPAMP = 72;
    const int DOTSTAR = 73;
    const int ARROWSTAR = 74;
    const int BITOR = 75;
    const int BITXOR = 76;
    const int AMP = 77;
    const int EQ = 78;
    const int NEQ = 79;
    const int LEQ = 80;
    const int GEQ = 81;
    const int SHIFTLEFT = 82;
    const int SHIFTRIGHT = 83;
    const int PLUS = 84;
    const int MINUS = 85;
    const int STAR = 86;
    const int DIV = 87;
    const int REM = 88;
    const int PLUSPLUS = 89;
    const int MINUSMINUS = 90;
    const int CPL = 91;
    const int DOT = 92;
    const int ARROW = 93;
    const int QUEST = 94;
    const int LPAREN = 95;
    const int RPAREN = 96;
    const int LBRACE = 97;
    const int RBRACE = 98;
    const int LBRACKET = 99;
    const int RBRACKET = 100;
    const int LANGLE = 101;
    const int RANGLE = 102;
    const int ELLIPSIS = 103;
    const int COLONCOLON = 104;
    const int COLON = 105;
    const int SEMICOLON = 106;
    const int HASH = 107;
    const int COMMA = 108;
    const int ASSIGN = 109;
    const int MULASSIGN = 110;
    const int DIVASSIGN = 111;
    const int REMASSIGN = 112;
    const int PLUSASSIGN = 113;
    const int MINUSASSIGN = 114;
    const int SHIFTLEFTASSIGN = 115;
    const int SHIFTRIGHTASSIGN = 116;
    const int ANDASSIGN = 117;
    const int XORASSIGN = 118;
    const int ORASSIGN = 119;

    void InitTokenIdMap();
    int GetTokenId(const std::u32string& tokenName);
    const char* GetTokenName(int tokenId);
    const char* GetTokenInfo(int tokenId);
}
#endif
