#ifndef ParserFileTokens_HPP
#define ParserFileTokens_HPP

// this file has been automatically generated from 'C:/work/soulng/soulng/spg/ParserFileLexer.lexer' using soulng lexer generator slg version 3.1.0

#include <string>

namespace ParserFileTokens
{
    const int END = 0;
    const int PARSER = 1;
    const int API = 2;
    const int INCLUDE = 3;
    const int MAIN = 4;
    const int START = 5;
    const int NOTHROW = 6;
    const int STATE = 7;
    const int FARTHEST_ERROR = 8;
    const int USELEXER = 9;
    const int RULEINFO = 10;
    const int EMPTY = 11;
    const int ANY = 12;
    const int VAR = 13;
    const int CPPPREFIX = 14;
    const int HPPPREFIX = 15;
    const int FILEPATH = 16;
    const int PRODUCES = 17;
    const int EXCLAMATION = 18;
    const int AUTO = 19;
    const int REGISTER = 20;
    const int STATIC = 21;
    const int EXTERN = 22;
    const int MUTABLE = 23;
    const int CHAR = 24;
    const int WCHART = 25;
    const int BOOL = 26;
    const int SHORT = 27;
    const int INT = 28;
    const int LONG = 29;
    const int SIGNED = 30;
    const int UNSIGNED = 31;
    const int FLOAT = 32;
    const int DOUBLE = 33;
    const int VOID = 34;
    const int TYPEDEF = 35;
    const int CONST = 36;
    const int VOLATILE = 37;
    const int USING = 38;
    const int NAMESPACE = 39;
    const int THROW = 40;
    const int SIZEOF = 41;
    const int OPERATOR = 42;
    const int DYNAMICCAST = 43;
    const int STATICCAST = 44;
    const int REINTERPRETCAST = 45;
    const int CONSTCAST = 46;
    const int TYPEID = 47;
    const int THIS = 48;
    const int NEW = 49;
    const int DELETE = 50;
    const int TRUE = 51;
    const int FALSE = 52;
    const int NULLPTR = 53;
    const int CASE = 54;
    const int DEFAULT = 55;
    const int IF = 56;
    const int ELSE = 57;
    const int SWITCH = 58;
    const int WHILE = 59;
    const int DO = 60;
    const int FOR = 61;
    const int BREAK = 62;
    const int CONTINUE = 63;
    const int RETURN = 64;
    const int GOTO = 65;
    const int TRY = 66;
    const int CATCH = 67;
    const int ID = 68;
    const int INTLIT = 69;
    const int FLOATINGLIT = 70;
    const int CHARLIT = 71;
    const int STRINGLIT = 72;
    const int DISJUNCTION = 73;
    const int AMPAMP = 74;
    const int DOTSTAR = 75;
    const int ARROWSTAR = 76;
    const int BITOR = 77;
    const int BITXOR = 78;
    const int AMP = 79;
    const int EQ = 80;
    const int NEQ = 81;
    const int LEQ = 82;
    const int GEQ = 83;
    const int SHIFTLEFT = 84;
    const int SHIFTRIGHT = 85;
    const int PLUS = 86;
    const int MINUS = 87;
    const int STAR = 88;
    const int DIV = 89;
    const int REM = 90;
    const int PLUSPLUS = 91;
    const int MINUSMINUS = 92;
    const int CPL = 93;
    const int DOT = 94;
    const int ARROW = 95;
    const int QUEST = 96;
    const int LPAREN = 97;
    const int RPAREN = 98;
    const int LBRACE = 99;
    const int RBRACE = 100;
    const int LBRACKET = 101;
    const int RBRACKET = 102;
    const int LANGLE = 103;
    const int RANGLE = 104;
    const int ELLIPSIS = 105;
    const int COLONCOLON = 106;
    const int COLON = 107;
    const int SEMICOLON = 108;
    const int HASH = 109;
    const int COMMA = 110;
    const int ASSIGN = 111;
    const int MULASSIGN = 112;
    const int DIVASSIGN = 113;
    const int REMASSIGN = 114;
    const int PLUSASSIGN = 115;
    const int MINUSASSIGN = 116;
    const int SHIFTLEFTASSIGN = 117;
    const int SHIFTRIGHTASSIGN = 118;
    const int ANDASSIGN = 119;
    const int XORASSIGN = 120;
    const int ORASSIGN = 121;

    void InitTokenIdMap();
    int GetTokenId(const std::u32string& tokenName);
    const char* GetTokenName(int tokenId);
    const char* GetTokenInfo(int tokenId);
}
#endif
